### ISSUE TITLE
extended version, with full screen support

### ISSUE THREAD

**Issue by tomaskovacik** [arildlangseid/vw_t4_tcu_temp_to_fis#1]
hi, I have for few month your lib with support for full-screen support , check it out:

https://github.com/tomaskovacik/VAGFISWriter

more work need to be done, test, documentation, probably interrurp driven timing etc... 

I was thinking about extending your project to make it more "LCD library compatible" so we can then build easy "fistool" alternative maybe openfis :)) 

one picture and video of code in action: http://kovo-blog.blogspot.sk/2018/04/full-fis-over-3lb.html

if you split your library to separate repository, we can collaborate  on this

thx for your work :) 

t.

edit: so no responce from you, so I make it as separate arduino lib, with all needed files, also renamed it cose it works on all VAG cars and also on older then 2002

https://github.com/tomaskovacik/VAGFISWriter

again thx!

**Comment by arildlangseid** [comment]
Thanks for head-up!

Sorry - I missed your message here. This project is just for reference for me now and archived just to offer my findings to other as this project was based on other open-source projects mentioned.

Just checked out your project - and wow, very nice!!!

Good luck on your project! Good to see my work came to use for others :-)

Best regards,
Arild
